export const metadata = {
    title: 'Pokémon',
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
    return (
      <main className="mx-auto sm:max-w-[75%] md:max-w-[50%] lg:max-w-[40%]">
        {children}
      </main>
    )
  }