export const metadata = {
    title: 'Pokémon',
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
    return (
      <main className="mx-auto max-w-6xl p-4">
        {children}
      </main>
    )
  }